import Link from 'next/link';
import { Download, FileText, Database } from 'lucide-react';

export default function DownloadPage() {
  return (
    <div className="max-w-5xl mx-auto px-4 py-10">
      <div className="mb-10 text-center">
        <div className="w-20 h-20 bg-blue-100 text-[#0072B7] rounded-full flex items-center justify-center mx-auto mb-6">
          <Download className="w-10 h-10" />
        </div>
        <h1 className="text-4xl font-extrabold text-slate-800 mb-4">Data Access Portal</h1>
        <p className="text-xl text-slate-600 max-w-2xl mx-auto">
          Download the raw synthetic dataset generated by our statistical framework for your own analysis and humanitarian project planning.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-12">
        {/* Full Dataset */}
        <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 hover:shadow-md transition-shadow relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
            <Database className="w-32 h-32 text-[#0072B7]" />
          </div>
          <h2 className="text-2xl font-bold text-slate-800 mb-2">Production Dataset</h2>
          <p className="text-slate-500 mb-6 min-h-[50px]">
            Comprehensive demographic representation containing approximately 500,000 modeled individuals.
          </p>
          
          <ul className="mb-8 space-y-2 text-sm text-slate-600">
            <li className="flex items-center gap-2">✓ Household & Individual level data</li>
            <li className="flex items-center gap-2">✓ Full geographic distribution</li>
            <li className="flex items-center gap-2">✓ Size: ~50MB</li>
          </ul>

          <a href="/api/download/full" className="inline-flex w-full items-center justify-center gap-2 bg-[#0072B7] text-white py-3 px-6 rounded-lg font-bold hover:bg-[#005a92] transition-colors shadow-sm">
            <Download className="w-5 h-5" /> Download CSV
          </a>
        </div>

        {/* Sample Dataset */}
        <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 hover:shadow-md transition-shadow relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
            <FileText className="w-32 h-32 text-emerald-600" />
          </div>
          <h2 className="text-2xl font-bold text-slate-800 mb-2">Demo Dataset</h2>
          <p className="text-slate-500 mb-6 min-h-[50px]">
            A lightweight slice containing 50,000 households for rapid prototyping and testing.
          </p>
          
          <ul className="mb-8 space-y-2 text-sm text-slate-600">
            <li className="flex items-center gap-2">✓ Proportionate random sampling</li>
            <li className="flex items-center gap-2">✓ Ideal for Jupyter/Colab imports</li>
            <li className="flex items-center gap-2">✓ Size: ~10MB</li>
          </ul>

          <a href="/api/download/sample" className="inline-flex w-full items-center justify-center gap-2 bg-emerald-600 text-white py-3 px-6 rounded-lg font-bold hover:bg-emerald-700 transition-colors shadow-sm">
            <Download className="w-5 h-5" /> Download Sample
          </a>
        </div>
      </div>

      <div className="bg-slate-50 p-6 rounded-xl border border-slate-200">
        <h3 className="font-bold text-slate-800 mb-2">Licensing and Usage</h3>
        <p className="text-sm text-slate-600 mb-4">
          This data is provided under an Open Data framework specifically intended for humanitarian use cases, statistical modeling, and operational coordination tools. No attribution is required, but citation of primary sources listed in our methodology is recommended for published works.
        </p>
        <div className="flex items-center gap-4 text-xs font-mono text-slate-400 bg-slate-100 p-3 rounded">
          <span>Columns:</span> 
          <span>household_id</span> | <span>country</span> | <span>region_camp</span> | <span>family_size</span> | <span>members</span> | <span>head_age</span> | <span>head_gender</span> | <span>vulnerability_type</span>
        </div>
      </div>
    </div>
  );
}
